import type { WorkflowDefinition, WorkflowGraph } from "@/lib/workflow/types";

function jsonLiteral(value: unknown, indent = 2, depth = 1): string {
  const pad = " ".repeat(indent * depth);
  const parentPad = " ".repeat(indent * (depth - 1));

  if (value === null) return "null";
  if (value === undefined) return "undefined";
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }

  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    const items = value
      .map((item) => `${pad}${jsonLiteral(item, indent, depth + 1)}`)
      .join(",\n");
    return `[\n${items}\n${parentPad}]`;
  }

  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>).filter(
      ([, entryValue]) => entryValue !== undefined,
    );
    if (entries.length === 0) return "{}";
    const body = entries
      .map(([key, entryValue]) => {
        const safeKey = /^[a-zA-Z_$][\w$]*$/.test(key)
          ? key
          : JSON.stringify(key);
        return `${pad}${safeKey}: ${jsonLiteral(entryValue, indent, depth + 1)}`;
      })
      .join(",\n");
    return `{\n${body}\n${parentPad}}`;
  }

  return JSON.stringify(value);
}

export function serializeWorkflowGraphToTs(
  workflow: Pick<WorkflowDefinition, "name" | "slug" | "description"> & {
    draftGraph: WorkflowGraph;
  },
): string {
  const header = `// Auto-generated by Workerflow. Re-import via the editor to restore.
import type { WorkflowGraph } from "@/lib/workflow/types";

export const workflowName = ${JSON.stringify(workflow.name)};
export const workflowSlug = ${JSON.stringify(workflow.slug)};
export const workflowDescription = ${JSON.stringify(workflow.description)};

export const workflowGraph: WorkflowGraph = ${jsonLiteral(workflow.draftGraph)};

export default workflowGraph;
`;
  return header;
}

export function downloadWorkflowAsTs(
  workflow: Pick<WorkflowDefinition, "name" | "slug" | "description"> & {
    draftGraph: WorkflowGraph;
  },
) {
  const source = serializeWorkflowGraphToTs(workflow);
  const blob = new Blob([source], { type: "text/typescript;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${workflow.slug || "workflow"}.workflow.ts`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
