/**
 * Plugin Index
 *
 * This file is auto-generated by `pnpm discover-plugins`.
 * Do not edit it manually.
 */

import "./anthropic/index.ts";
import "./core/index.ts";
import "./discord/index.ts";
import "./fal/index.ts";
import "./github/index.ts";
import "./linear/index.ts";
import "./openai/index.ts";
import "./openrouter/index.ts";
import "./planetscale/index.ts";

export const pluginIds = [
  "anthropic",
  "core",
  "discord",
  "fal",
  "github",
  "linear",
  "openai",
  "openrouter",
  "planetscale",
] as const;

export type PluginId = (typeof pluginIds)[number];
