#!/usr/bin/env node

import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const rootDir = process.cwd();
const pluginsDir = join(rootDir, "plugins");
const outputFile = join(pluginsDir, "index.ts");

function discoverPlugins() {
  return readdirSync(pluginsDir)
    .filter((entry) => {
      if (
        entry.startsWith(".") ||
        entry.startsWith("_") ||
        entry === "index.ts" ||
        entry === "runtime.ts" ||
        entry === "types.ts" ||
        entry === "AGENTS.md"
      ) {
        return false;
      }

      const fullPath = join(pluginsDir, entry);
      try {
        return statSync(fullPath).isDirectory();
      } catch {
        return false;
      }
    })
    .sort((left, right) => left.localeCompare(right));
}

function createIndexContent(pluginIds) {
  const imports = pluginIds
    .map((pluginId) => `import "./${pluginId}/index.ts";`)
    .join("\n");
  const pluginList = pluginIds.map((pluginId) => `  "${pluginId}",`).join("\n");

  return `/**
 * Plugin Index
 *
 * This file is auto-generated by \`pnpm discover-plugins\`.
 * Do not edit it manually.
 */

${imports || "// No plugins discovered."}

export const pluginIds = [
${pluginList}
] as const;

export type PluginId = (typeof pluginIds)[number];
`;
}

const pluginIds = discoverPlugins();
writeFileSync(outputFile, createIndexContent(pluginIds), "utf8");
console.log(`Discovered ${pluginIds.length} plugin(s).`);
